/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CODIGOS;

import java.awt.event.ActionEvent;
import java.util.Random;
import javax.swing.Timer;

/**
 *
 * @author Ismael Ribeiro
 */
public class Tela extends javax.swing.JFrame {
    
    public static int y, x, contador,contador2, na;
    public int velocidade_do_movimento = 5;
    
    public Timer timer, timer2;
    
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        inimigo2 = new javax.swing.JLabel();
        inimigo1 = new javax.swing.JLabel();
        inimigo3 = new javax.swing.JLabel();
        PAPEL_DE_PAREDE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inimigo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODIGOS/Imagens/ghost_icon_by_mechamushroom-d4x5owh.gif"))); // NOI18N
        inimigo2.setFocusable(false);
        jDesktopPane1.add(inimigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        inimigo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODIGOS/Imagens/ghost_icon_by_mechamushroom-d4x5owh.gif"))); // NOI18N
        inimigo1.setFocusable(false);
        jDesktopPane1.add(inimigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        inimigo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODIGOS/Imagens/ghost_icon_by_mechamushroom-d4x5owh.gif"))); // NOI18N
        inimigo3.setFocusable(false);
        jDesktopPane1.add(inimigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        PAPEL_DE_PAREDE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CODIGOS/Imagens/castelo2.jpg"))); // NOI18N
        jDesktopPane1.add(PAPEL_DE_PAREDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        //1220 660
        
        inimigo1.setVisible(true);
        inimigo3.setVisible(false);
        inimigo2.setVisible(false);
        
        this.setExtendedState(MAXIMIZED_BOTH);//DEFINE A JANELA PARA INICIAR MAXIMIZADA
        
        timer = new Timer(1, (ActionEvent e) -> {
            
            contador++;
            
            if(inimigo1.getX() < 1330){
                
                inimigo1.setLocation(1+contador, na);
                
                
            }else{
                
                contador = 1; 
                
                Random num1 = new Random();
                na = num1.nextInt(661);//NUMEROS ALEATORIOS ENTRE 0 E 660
                
                inimigo1.setLocation(0, na);
                
            }
            
        });
        
        timer.start();
        
        timer = new Timer(1000, (ActionEvent e) -> {
            
           
            
        });
        
        timer.start();
        
        /*y = ghost.getY();
        x = ghost.getX();
        
         KeyboardFocusManager.getCurrentKeyboardFocusManager()
            .addKeyEventDispatcher(new KeyEventDispatcher() {
                @Override
                public boolean dispatchKeyEvent(KeyEvent event) {
                    if(event.getID() == KeyEvent.KEY_PRESSED && event.getKeyCode() == 38){//cima
                            
                            y = y-velocidade_do_movimento;
                            ghost.setLocation(x, y);
                        
                           return true;
                     }
                    else
                        if(event.getID() == KeyEvent.KEY_PRESSED && event.getKeyCode() == 40){//baixo
                            
                            y = y+velocidade_do_movimento;
                            ghost.setLocation(x, y);
                            
                           return true;
                     }
                    else
                        if(event.getID() == KeyEvent.KEY_PRESSED && event.getKeyCode() == 39){//direita
                           
                           x = x+velocidade_do_movimento;
                           ghost.setLocation(x, y); 
                            
                           return true;
                     }
                    else
                        if(event.getID() == KeyEvent.KEY_PRESSED && event.getKeyCode() == 37){//esquerda
                           
                           x = x-velocidade_do_movimento;
                           ghost.setLocation(x, y); 
                            
                           return true;
                     }
                     return false;
                }
        });*/
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PAPEL_DE_PAREDE;
    private javax.swing.JLabel inimigo1;
    private javax.swing.JLabel inimigo2;
    private javax.swing.JLabel inimigo3;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
